name: PlatformIO CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    container:
      image: petrows/arduino-vid6608:e9879e0
      options: -u 2025:2025
    strategy:
      matrix:
        example: [examples/RandomMove/RandomMove.cpp]
    steps:
      - uses: actions/checkout@v4
      - name: Build PlatformIO examples
        run: |
            echo "::group::pio ci"
            # We have to enforce $HOME here, to skip runtime installation
            # See Dockerfile for static environment
            export HOME=/opt/home
            export CI=true

            pio ci --project-conf platformio.ini -l src/
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
  check:
    runs-on: self-hosted
    container:
      image: petrows/arduino-vid6608:e9879e0
      options: -u 2025:2025
    steps:
      - uses: actions/checkout@v4
      - name: Run PlatformIO checks
        run: |
            echo "::group::pio check"
            # We have to enforce $HOME here, to skip runtime installation
            # See Dockerfile for static environment
            export HOME=/opt/home
            export CI=true

            pio check
